from . import res_config_settings
from . import res_partner
from . import office_inspection
from . import incident_report
from . import fire_extinguisher
from . import accident_investigation
from . import vehicle_inspection
from . import insurance_claim
from . import insurance_type
from . import employee_suggestion
from . import employee_safety_induction 